#ifndef __FIREFLY_SM_FIREFLY_H__
#define __FIREFLY_SM_FIREFLY_H__

#include <stdint.h>

#include "task.h"

enum sm_states_firefly
{
  SM_FIREFLY_INIT,
  SM_FIREFLY_FLU_BLINK_NONE,
  SM_FIREFLY_FLU_BLINK_5S,
  SM_FIREFLY_FLU_BLINK_15S,
  SM_FIREFLY_WHITE_BLINK_NONE,
  SM_FIREFLY_WHITE_BLINK_1S, 
  SM_FIREFLY_WHITE_BLINK_5S, 
  SM_FIREFLY_RED_BLINK_NONE,
  SM_FIREFLY_RED_BLINK_1S,  
  SM_FIREFLY_RED_BLINK_5S,
  SM_FIREFLY_ORG_BLINK_NONE,
  SM_FIREFLY_ORG_BLINK_1S,
  SM_FIREFLY_ORG_BLINK_5S,
  SM_FIREFLY_UTR_BLINK_NONE,  
  SM_FIREFLY_POWER_OFF
};

const struct sm_state_slot code sm_function_firefly[];

#endif
